# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc59440df47b397d0508cf805c7e842abe97779740e45e4b7bfc6b3ce8244944eda62853577675e932536c0fbbcea0fe73953124027e2a2a3c43e507e57916f9

test:
  secret_key_base: f8da4c2f5008f7f86b7efa4da0d0b4fd978e3aeb9b022becb92df7de2ae27599ad62262bef260a802e9d323ff812bb90e5a2b19a53c84578e9d75e2ad88dda70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
